language: r
r:
  - oldrel
  - release
  - devel
sudo: false
cache: packages

# Only report coverage for the release version
after_success:
  - test $TRAVIS_R_VERSION_STRING = 'release' && Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: never
    on_failure: always
